/*
 * Step 12
 *
 * Exact decomposition of the 24 cyclic C12 subgroups by:
 *
 *   1. their C4 intersection with K32;
 *   2. their order-3 image line in G288/K32 ≅ C3 x C3.
 *
 * The question tested here is whether
 *
 *   24 = 6 x 4
 *
 * occurs as the full Cartesian product of six C4 directions and
 * four quotient lines.
 */

import {
  G288_IDENTITY,
  g288ElementOrder,
} from "./group288.mjs";

import {
  powerG288,
} from "./spectralClassification.mjs";

import {
  K32,
  isK32Element,
} from "./subgroups.mjs";

import {
  cosetContaining,
  quotientCoordinates,
} from "./quotientC3xC3.mjs";

import {
  C12_SUBGROUPS,
} from "./cyclicSubgroups.mjs";


function elementSetKey(
  elements
) {
  return elements
    .map(
      (element) =>
        element.key
    )
    .sort()
    .join("||");
}


function mod3(
  value
) {
  return (
    (value % 3) + 3
  ) % 3;
}


function coordinateKey(
  coordinates
) {
  return (
    `${mod3(coordinates.a)},` +
    `${mod3(coordinates.b)}`
  );
}


/*
 * A 1-dimensional subspace of F3^2 has two nonzero points v and -v.
 * We use the sorted pair as an intrinsic line key.
 */
export function quotientLineKeyFromCoordinates(
  coordinates
) {
  const a =
    mod3(
      coordinates.a
    );

  const b =
    mod3(
      coordinates.b
    );

  if (
    a === 0 &&
    b === 0
  ) {
    throw new RangeError(
      "The zero quotient coordinate does not determine a projective line."
    );
  }

  const opposite =
    Object.freeze({
      a:
        mod3(-a),
      b:
        mod3(-b),
    });

  return [
    coordinateKey({
      a,
      b,
    }),
    coordinateKey(
      opposite
    ),
  ]
    .sort()
    .join("|");
}


export const QUOTIENT_LINES =
  Object.freeze([
    Object.freeze({
      label: "line-1",
      representative:
        Object.freeze({
          a: 1,
          b: 0,
        }),
    }),

    Object.freeze({
      label: "line-2",
      representative:
        Object.freeze({
          a: 0,
          b: 1,
        }),
    }),

    Object.freeze({
      label: "line-3",
      representative:
        Object.freeze({
          a: 1,
          b: 1,
        }),
    }),

    Object.freeze({
      label: "line-4",
      representative:
        Object.freeze({
          a: 1,
          b: 2,
        }),
    }),
  ].map(
    (line) =>
      Object.freeze({
        ...line,
        key:
          quotientLineKeyFromCoordinates(
            line.representative
          ),
      })
  )
);


const QUOTIENT_LINE_BY_KEY =
  new Map(
    QUOTIENT_LINES.map(
      (line) => [
        line.key,
        line,
      ]
    )
  );


/*
 * Build every distinct cyclic C4 subgroup of K32 generated by
 * an order-4 element.
 */
function cyclicC4GeneratedBy(
  generator
) {
  const elements = [];

  for (
    let exponent = 0;
    exponent < 4;
    exponent += 1
  ) {
    elements.push(
      powerG288(
        generator,
        exponent
      )
    );
  }

  return Object.freeze({
    generator,

    elements:
      Object.freeze(
        elements
      ),

    key:
      elementSetKey(
        elements
      ),
  });
}


function buildK32C4Directions() {
  const byKey =
    new Map();

  for (
    const element of K32
  ) {
    if (
      g288ElementOrder(
        element
      ) !== 4
    ) {
      continue;
    }

    const subgroup =
      cyclicC4GeneratedBy(
        element
      );

    if (
      !byKey.has(
        subgroup.key
      )
    ) {
      byKey.set(
        subgroup.key,
        subgroup
      );
    }
  }

  return [
    ...byKey.values(),
  ]
    .sort(
      (left, right) =>
        left.key.localeCompare(
          right.key
        )
    )
    .map(
      (subgroup, index) =>
        Object.freeze({
          ...subgroup,
          directionIndex:
            index,
          label:
            `C4-${index + 1}`,
        })
    );
}


export const K32_C4_DIRECTIONS =
  Object.freeze(
    buildK32C4Directions()
  );


const C4_DIRECTION_BY_KEY =
  new Map(
    K32_C4_DIRECTIONS.map(
      (direction) => [
        direction.key,
        direction,
      ]
    )
  );


export function c4IntersectionForC12(
  subgroup
) {
  const intersection =
    subgroup.elements.filter(
      isK32Element
    );

  return Object.freeze(
    intersection
  );
}


export function quotientLineForC12(
  subgroup
) {
  /*
   * Any primitive order-12 generator has nonzero image of order 3
   * in C3 x C3. Its two possible nonzero coordinates determine
   * the same projective line.
   */
  const generator =
    subgroup.generator;

  const coset =
    cosetContaining(
      generator
    );

  if (!coset) {
    throw new Error(
      "C12 generator has no quotient coset."
    );
  }

  const coordinates =
    quotientCoordinates(
      coset
    );

  if (!coordinates) {
    throw new Error(
      "C12 generator quotient coset has no coordinates."
    );
  }

  const key =
    quotientLineKeyFromCoordinates(
      coordinates
    );

  const line =
    QUOTIENT_LINE_BY_KEY.get(
      key
    );

  if (!line) {
    throw new Error(
      `Unknown quotient line ${key}.`
    );
  }

  return line;
}


function buildC12DirectionLineRecords() {
  return C12_SUBGROUPS.map(
    (subgroup, index) => {
      const intersection =
        c4IntersectionForC12(
          subgroup
        );

      const intersectionKey =
        elementSetKey(
          intersection
        );

      const direction =
        C4_DIRECTION_BY_KEY.get(
          intersectionKey
        );

      if (!direction) {
        throw new Error(
          "C12 ∩ K32 is not one of the derived C4 directions."
        );
      }

      const quotientLine =
        quotientLineForC12(
          subgroup
        );

      return Object.freeze({
        c12Index:
          index,

        subgroup,

        intersection:
          Object.freeze(
            intersection
          ),

        c4Direction:
          direction,

        quotientLine,

        pairKey:
          `${direction.label}|${quotientLine.label}`,
      });
    }
  );
}


export const C12_DIRECTION_LINE_RECORDS =
  Object.freeze(
    buildC12DirectionLineRecords()
  );


export function validateC12DirectionLineStructure() {
  if (
    K32_C4_DIRECTIONS.length !==
    6
  ) {
    throw new Error(
      `Expected six distinct C4 directions in K32; found ${K32_C4_DIRECTIONS.length}.`
    );
  }

  if (
    QUOTIENT_LINES.length !==
    4
  ) {
    throw new Error(
      `Expected four quotient lines; found ${QUOTIENT_LINES.length}.`
    );
  }

  if (
    C12_DIRECTION_LINE_RECORDS.length !==
    24
  ) {
    throw new Error(
      `Expected 24 C12 direction-line records; found ${C12_DIRECTION_LINE_RECORDS.length}.`
    );
  }

  /*
   * Verify each derived C4 really is a four-element cyclic subgroup
   * contained in K32.
   */
  const k32Keys =
    new Set(
      K32.map(
        (element) =>
          element.key
      )
    );

  for (
    const direction of
      K32_C4_DIRECTIONS
  ) {
    if (
      direction.elements.length !==
      4
    ) {
      throw new Error(
        `${direction.label} does not contain four elements.`
      );
    }

    if (
      !direction.elements.every(
        (element) =>
          k32Keys.has(
            element.key
          )
      )
    ) {
      throw new Error(
        `${direction.label} is not contained in K32.`
      );
    }

    if (
      !direction.elements.some(
        (element) =>
          element.key ===
          G288_IDENTITY.key
      )
    ) {
      throw new Error(
        `${direction.label} does not contain the identity.`
      );
    }

    const orders =
      direction.elements
        .map(
          g288ElementOrder
        )
        .sort(
          (a, b) =>
            a - b
        );

    if (
      orders.join(",") !==
      "1,2,4,4"
    ) {
      throw new Error(
        `${direction.label} does not have C4 order pattern 1,2,4,4.`
      );
    }
  }

  /*
   * Every C12 must intersect K32 in exactly one of these six C4s.
   */
  for (
    const record of
      C12_DIRECTION_LINE_RECORDS
  ) {
    if (
      record.intersection.length !==
      4
    ) {
      throw new Error(
        `C12-${record.c12Index + 1} intersects K32 in ${record.intersection.length} elements instead of 4.`
      );
    }

    const intersectionOrders =
      record.intersection
        .map(
          g288ElementOrder
        )
        .sort(
          (a, b) =>
            a - b
        );

    if (
      intersectionOrders.join(",") !==
      "1,2,4,4"
    ) {
      throw new Error(
        `C12-${record.c12Index + 1} intersection with K32 is not C4.`
      );
    }
  }

  /*
   * Test the central hypothesis:
   *
   * all six C4 directions crossed with all four quotient lines
   * occur exactly once.
   */
  const pairCounts =
    new Map();

  for (
    const record of
      C12_DIRECTION_LINE_RECORDS
  ) {
    pairCounts.set(
      record.pairKey,
      (
        pairCounts.get(
          record.pairKey
        ) ??
        0
      ) + 1
    );
  }

  if (
    pairCounts.size !==
    24
  ) {
    throw new Error(
      `Expected 24 distinct direction-line pairs; found ${pairCounts.size}.`
    );
  }

  for (
    const direction of
      K32_C4_DIRECTIONS
  ) {
    for (
      const line of
        QUOTIENT_LINES
    ) {
      const pairKey =
        `${direction.label}|${line.label}`;

      if (
        pairCounts.get(
          pairKey
        ) !== 1
      ) {
        throw new Error(
          `Expected exactly one C12 for ${pairKey}; found ${pairCounts.get(pairKey) ?? 0}.`
        );
      }
    }
  }

  /*
   * Each C4 direction must therefore occur in four C12s,
   * and each quotient line in six.
   */
  const directionCounts =
    new Map();

  const lineCounts =
    new Map();

  for (
    const record of
      C12_DIRECTION_LINE_RECORDS
  ) {
    directionCounts.set(
      record.c4Direction.label,
      (
        directionCounts.get(
          record.c4Direction.label
        ) ??
        0
      ) + 1
    );

    lineCounts.set(
      record.quotientLine.label,
      (
        lineCounts.get(
          record.quotientLine.label
        ) ??
        0
      ) + 1
    );
  }

  for (
    const direction of
      K32_C4_DIRECTIONS
  ) {
    if (
      directionCounts.get(
        direction.label
      ) !== 4
    ) {
      throw new Error(
        `${direction.label} does not occur in exactly four C12 subgroups.`
      );
    }
  }

  for (
    const line of
      QUOTIENT_LINES
  ) {
    if (
      lineCounts.get(
        line.label
      ) !== 6
    ) {
      throw new Error(
        `${line.label} does not occur in exactly six C12 subgroups.`
      );
    }
  }

  return Object.freeze({
    c4DirectionCount:
      K32_C4_DIRECTIONS.length,

    quotientLineCount:
      QUOTIENT_LINES.length,

    c12Count:
      C12_DIRECTION_LINE_RECORDS.length,

    distinctPairCount:
      pairCounts.size,

    directionCounts:
      Object.freeze(
        Object.fromEntries(
          directionCounts
        )
      ),

    lineCounts:
      Object.freeze(
        Object.fromEntries(
          lineCounts
        )
      ),
  });
}
