'use client';

import LayoutWrapper from '@/components/LayoutWrapper';
import '../globals.css';

export default function CoherentUnits() {
  return (
    <LayoutWrapper>
  <div className="coherent-units-page">
    <div
  className="symbol-overlay"
  style={{
    left: 0,
    width: "100vw",
  }}
/>

    <div
  className="partition-content"
  style={{
    width: "min(1750px, calc(100vw - var(--sidebar-width) - 4rem))",
    maxWidth: "none",
  }}
>
      <div className="legend-title">coherent units</div>

      <div className="equation-description">
        Measurement began as a collection of largely unrelated human conventions—feet,
        hours, weights, temperatures. Physics progressively revealed that a useful system
        cannot merely assign names to quantities: its units must close under the equations
        of Nature. If force is mass × acceleration, the unit of force should emerge from the units
        of mass, length, and time without an arbitrary correction factor. If energy is
        force × distance, its unit should follow from the same system. This is the essential
        meaning of a <i>coherent</i> system of units.
      </div>

      <div style={{ height: '2.0rem' }} />

      <div
        style={{
          textAlign: 'center',
          fontSize: '1.2rem',
          fontWeight: 'normal',
          margin: '0rem 0 1.25rem',
        }}
      >
        the discovery of coherence
      </div>

<div
        className="equation-description"
        style={{
          textAlign: 'center',
          fontStyle: 'italic',
        }}
      >
        Coherence means that the equations, not convention, determine how the units fit together.
      </div>

      <div style={{ height: '1.75rem' }} />

      <div className="equation-description">
      The deeper importance of measurement is that measured quantities are not isolated. Once physical relationships are expressed quantitatively, the quantities begin to constrain one another. Galileo’s analysis of falling bodies made this especially clear: distance, time, velocity, and acceleration form a connected system rather than a collection of independent observations.
      </div>

      <div className="equation-description">
        In geometry and mechanics, length and time first appear as distinct primitive
        measurements. Newtonian mechanics ties them together through velocity and
        acceleration, while mass introduces another independent dimension. Force,
        momentum, energy, and the other mechanical quantities then arise as combinations
        of these underlying dimensions.
      </div>

      <div className="equation-description">
        Electromagnetism made the need for coherence much harder to ignore. Gauss,
        Weber, Maxwell, and others found that electrical and magnetic quantities could
        not remain an unrelated collection of measures: the equations themselves impose
        relations among them. The nineteenth-century absolute systems of units were
        attempts to make the measurement system reflect the algebraic structure of the
        physical laws.
      </div>

      <div className="equation-description">
        Dimensional analysis made this principle explicit. An equation whose dimensions
        do not balance can be rejected before any numerical measurement is made.
        Coherence therefore does more than simplify notation: it constrains which
        mathematical statements can even represent physical relations. Dimensional consistency is thus, a requirement of physical law.
      </div>

      <div className="equation-description">
        With Giorgi&apos;s MKS proposal and eventually the International System of Units,
        coherence became an explicit design principle. Derived units are products of
        powers of the base units without additional numerical conversion factors.
        Force, energy, power, electric potential, resistance, and the rest are not
        independent conventions; they are generated by the dimensional structure of
        the system.
      </div>

      <div className="equation-description">
        In relativity space and time are no longer separate backgrounds for
        physical events: <i>x</i> and <i>ct</i> belong to a common spacetime geometry,
        joined by the invariant speed of light. The meter is therefore realized through the second together with an invariant
        of Nature. In this concrete metrological sense, our unit of space is now defined
        through our unit of time and the fixed value of <i>c</i>. What once appeared to be two separate standards of measurement is revealed as a constrained relationship. Likewise, every constant of Nature prescribes a binding relationship in the dimensions of physical reality.
      </div>

      <div style={{ height: '2.5rem' }} />

      <div
        style={{
          textAlign: 'center',
          fontSize: '1.2rem',
          fontWeight: 'normal',
          margin: '0rem 0 1.25rem',
        }}
      >
        coherent units of atomic logic
      </div>

      <div className="equation-description">
        A coherent system is therefore more than a common language for measurement.
        Its units reproduce the dimensional structure of the laws themselves. The
        quantities governing persistent atomic constructions reveal a minimal
        coherent basis.
      </div>

      <div style={{ height: '1.25rem' }} />

      <div className="equation-description">
        There are <img
            src="/equations/red-5.svg"
            alt="5"
            style={{ height: '13px', width: 'auto', display: 'inline-block', position: 'relative', top: '-2px' }}
          /> coherent units (or bases) of atomic logic: the second, meter, coulomb,
        kelvin, and kilogram. Each of these bases defines a unit in the internally
        consistent constructive logic of persistent forms (atoms).
      </div>

      <div style={{ height: '2.5rem' }} />

      <div className="equation-line" style={{ marginLeft: '-0.0rem' }}>
        <img
          src="/equations/5_units.svg"
          alt="5 coherent units"
          style={{ height: '144px', width: 'auto' }}
        />
      </div>

      <div style={{ height: '1.5rem' }} />

      <div className="equation-description">
        Combining those <img
            src="/equations/red-5.svg"
            alt="5"
            style={{ height: '13px', width: 'auto', display: 'inline-block', position: 'relative', top: '-2px' }}
          /> coherent units—without any scalars—gives us the composite units of physics and chemistry.
        All of these units work in unison, logically capturing the action parameters of allowed atomic exchanges.
      </div>

      <div style={{ height: '2.5rem' }} />

      <div style={{ textAlign: 'center', fontSize: '1.2rem', fontWeight: 'normal', marginBottom: '-0.0rem' }}>
  composite units of atomic logic
</div>

<div className="equation-line" style={{ marginTop: '0rem', marginLeft: '0rem' }}>
  <img
    src="/equations/composite_units.svg"
    alt="the composite units"
    style={{ height: '200px', width: 'auto', marginTop: '0rem' }}
  />
</div>

        <div style={{ height: '2.0rem' }} />

      <div className="equation-description">
        There are also <img
            src="/equations/red-5.svg"
            alt="5"
            style={{ height: '13px', width: 'auto', display: 'inline-block', position: 'relative', top: '-2px' }}
          /> derived units of atomic logic, the: megahertz, femtometer, electron-volt, megaelectron-volt, and the gigaelectron-volt.
        These are defined as products of powers of the base units (or combinations of the base units) without any additional numerical factor other than one.
        That is, every derived unit has a value of {' '}
  <a
    href="https://en.wikipedia.org/wiki/International_System_of_Units?"
    target="_blank"
    rel="noopener noreferrer"
    style={{
      color: 'inherit',
      textDecoration: 'none',
    }}
    onMouseOver={e => (e.target.style.color = 'yellow')}
    onMouseOut={e => (e.target.style.color = 'inherit')}
  >
    1 raised to some power of 10
  </a>—making them coherent with the rest of the units of atomic logic.
      </div>

      <div style={{ height: '2.5rem' }} />

      <div style={{ textAlign: 'center', fontSize: '1.2rem', fontWeight: 'normal', margin: '0rem 0 0rem' }}>
  derived units of atomic logic
</div>

      <div style={{ height: '1.5rem' }} />

      <div className="equation-line" style={{ marginLeft: '-0.0rem' }}>
          <img
            src="/equations/derived_units.svg"
            alt="derived units"
            style={{ height: '170px', width: 'auto' }}
          />
        </div>

      <div style={{ height: '2.0rem' }} />

      <div className="equation-description">
        The mole is different in kind from these dimensional units: it represents an amount found to be special in atomic constructions rather than an additional physical dimension.
        The candela is a unit of luminous intensity—an amount of lumens (a unit based on the sensitivity of the human eye) divided by 4<img
            src="/equations/pi.svg"
            alt="pi"
            style={{ height: '9px', width: 'auto', display: 'inline-block', position: 'relative', top: '-1px' }}
          /> steradians (the geometric unit of solid angle).
      </div>

      <div style={{ height: '13.0rem' }} />

    </div>
  </div>
</LayoutWrapper>
  );
}
